INSERT INTO user (username, password) VALUES ("admin", "admin");
INSERT INTO user (username, password) VALUES ("user", "user");
INSERT INTO user_group (name) VALUE ("admins");
INSERT INTO user_group (name) VALUE ("users");
INSERT INTO user_groups (user, groups) VALUES (1, 1);
INSERT INTO user_groups (user, groups) VALUES (2, 2);
INSERT INTO menu_item (title, type) VALUES ("some calendar", 'CALENDAR');
INSERT INTO menu_item (title, type) VALUES ("some news", 'NEWS');
INSERT INTO menu_item (title, type) VALUES ("some form", 'FORM');
INSERT INTO user_group_menu_items (user_group, menu_items) VALUES (1, 1);
INSERT INTO user_group_menu_items (user_group, menu_items) VALUES (1, 2);
INSERT INTO user_group_menu_items (user_group, menu_items) VALUES (1, 3);
INSERT INTO user_group_menu_items (user_group, menu_items) VALUES (2, 1);
INSERT INTO user_group_menu_items (user_group, menu_items) VALUES (2, 3);
INSERT INTO news (category, title, content) VALUES (2, "First news", "First news some content");
INSERT INTO news (category, title, content) VALUES (2, "Second news", "Second news has some content also");
INSERT INTO news (category, title, content) VALUES (2, "Another news", "Another news should have some content also");
INSERT INTO event (category, start_date, end_date, name) VALUES (1, '2016-01-01 20:00:00', '2016-01-02 20:00:00', 'New year event');
INSERT INTO event (category, start_date, end_date, name) VALUES (1, '2016-02-03 19:00:00', '2016-03-03 20:00:00', 'Very happy month');
INSERT INTO event (category, start_date, end_date, name) VALUES (1, '2016-04-01 00:00:00', '2016-04-01 23:59:59', 'Prima Aprilis');
INSERT INTO event (category, start_date, end_date, name) VALUES (1, '2016-05-01 12:00:00', '2016-05-01 20:00:00', 'Work celebration');